Karm/mandrel-integration-tests

- apps/timezones/pom.xml
- apps/timezones/src/main/java/timezone/Main.java
- pom.xml
- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Apps.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Logs.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Mandrel 20.1
============
```
[ERROR] Failures:
[ERROR]   AppReproducersTest.timezonesBakedIn:194 `d’Europe centrale' string was expected.
There might be a problem with timezones inclusion.
See https://github.com/oracle/graal/issues/2776 ==> expected: <true> but was: <false>
[INFO]
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
```
Mandrel 20.2
============
```
[o.g.t.i.AppReproducersTest] (timezonesBakedIn) Testing app: TIMEZONES
[o.g.t.i.AppReproducersTest] (timezonesBakedIn) Running...
[o.g.t.i.u.Logs] (checkLog) build-and-run.log log for timezonesBakedIn contains whitelisted error:
`WARNING: Using an older version of the labsjdk-11.'
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 87.836 s - in org.graalvm.tests.integration.AppReproducersTest
```
> Adds test for graal/issues/2776, Timezones

- apps/quarkus-full-microprofile/pom.xml
- apps/quarkus-full-microprofile/src/main/resources/application.properties
additionalBuildArgs is deprecated (see https://github.com/quarkusio/quarkus/issues/12666#issuecomment-707596054)
> Use quarkus.native.additional-build-args instead of additionalBuildArgs

- README.md
`libffi-devel` as of 20.1.0.3.Final is no longer needed (https://github.com/graalvm/mandrel/issues/158)
> Remove obsolete libffi-devel dependency

- pom.xml
Fixes https://github.com/oracle/graal/issues/3140 when using GraalVM/Mandrel 20.3.1 and 21.0.x
> Update micronaut to 2.3.0

- apps/versions/pom.xml
- pom.xml
- testsuite/pom.xml
- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/RuntimesSmokeTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/IfMandrelVersion.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/MandrelVersionCondition.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/UsedVersion.java
Examples:
```
@IfMandrelVersion(min = "20.1", max="20.3.2")
@IfMandrelVersion(min = "21.1", inContainer = true)
@IfMandrelVersion(min = "20.1.0.4", max = "20.3.2")
@IfMandrelVersion(min = "21.1")
```
The actual comparator comes from Graal's own org.graalvm.home.Version.
The version detected is spit out in the log:
```
INFO  [o.g.t.i.u.v.UsedVersion] (getVersion) Running command [native-image, --version] to determine Mandrel version used.
INFO  [o.g.t.i.u.v.UsedVersion] (getVersion) The test suite runs with Mandrel version 20.3.2-final installed locally on PATH.
INFO  [o.g.t.i.u.v.UsedVersion] (getVersion) Running command [docker, run, -t, quay.io/quarkus/ubi-quarkus-mandrel:20.1-java11, native-image, --version] to determine Mandrel version used.
INFO  [o.g.t.i.u.v.UsedVersion] …
```
> Adds test method annotation IfMandrelVersion

- .github/workflows/builder_image_tests.yml
- .github/workflows/local_tests.yml
- pom.xml
- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/JFRTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/RuntimesSmokeTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Apps.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/ContainerNames.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Logs.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/MandrelVersionCondition.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/UsedVersion.java
JFR tests were limited to locally installed Mandrel and some options tests were limited to version 21.3.
This patch enabled JFR tests to be built in a builder container and lowers the min version to 21.2 since the patch for https://github.com/oracle/graal/issues/3638 was backported.
e.g. 
```
2021-10-01 14:17:34.848 INFO  [o.g.t.i.u.v.UsedVersion] (getVersion) The test suite runs with Mandrel version 21.2.0-0b3 in container.
2021-10-01 14:17:34.876 INFO  [o.g.t.i.JFRTest] (jfrOptionsSmoke) Testing app: JFR_OPTIONS_BUILDER_IMAGE
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 69.094 s <<< FAILURE! - in org.graalvm.tests.integration.JFRTest
[ERROR] jfrOptionsSmokeContainerTest{TestInfo}  Time elapsed: 39.958 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: …
```
> JFR tests are also built in a builder container now

- builder-image-apps/quarkus-vertx/quarkus_main.patch
- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
Closes: #63
Note: A potential issue with this patch is that it won't work with snapshots from Quarkus versions before the artifact renaming.
> The artifact quarkus-vertx-web is now named quarkus-reactive-routes

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/RuntimesSmokeTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/CP.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/IfMandrelVersion.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/MandrelVersionCondition.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/UsedVersion.java
Gets rid of false positive on ImageIO test when using e.g. images from registry.access.redhat.com.
> Recognizes LTS version in prod builder image, JDK version parsed

- .github/workflows/builder_image_tests.yml
- .github/workflows/local_tests.yml
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
`--allow-incomplete-classpath` will not be available starting from GraalVM/Mandrel 22.1
Fixes #76
> Ignore warning about --allow-incomplete-classpath in helidon quickstart

- .github/workflows/builder_image_tests.yml
- .github/workflows/testing_testsuite.yml
- testsuite/pom.xml
- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/IfMandrelVersion.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/MandrelVersionCondition.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/QuarkusVersion.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/UsedVersion.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/VersionsTest.java
Tested examples:
```java
@Test
@Tag("jdkVersionTest")
@Order(1)
@IfMandrelVersion(min = "21.3.1")
public void jdkVersionCheckA(TestInfo testInfo) {
System.out.println("KARM Running test "+testInfo.getTestMethod());
}
@Test
@Tag("jdkVersionTest")
@Order(2)
@IfMandrelVersion(min = "21.3.1", minJDK = "17")
public void jdkVersionCheckB(TestInfo testInfo) {
System.out.println("KARM Running test "+testInfo.getTestMethod());
}
@Test
@Tag("jdkVersionTest")
@Order(3)
@IfMandrelVersion(min = "22", minJDK = "17")
public void jdkVersionCheckC(TestInfo testInfo) {
System.out.println("KARM Running test "+testInfo.getTestMethod());
}
@Test
@Tag("jdkVersionTest")
@Order(4)
@IfMandrelVersion(min = "22", minJDK = "17.0.2")
public void jdkVersionCheckD(TestInfo testInfo) {
System.out.println("KARM Running …
```
> Adds minJDK and maxJDK to IfMandrelVersion annotation

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
libmanagement_ext.a added in 22.2 with
https://github.com/oracle/graal/commit/a0e6a3aeb8b63f6c06dc3554c342075534d90796
See 
https://github.com/graalvm/mandrel/runs/5844449678?check_suite_focus=true#step:10:18269 for a failure with 22.2-dev
> Fix ImageIO test to work with 22.2-dev

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
The resources fix https://github.com/oracle/graal/commit/7c4257f3f88d7cf2a368b92c714b8d55b44f36cd
is backported to 22.1 as well
> Fix resources tests for 22.1

- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Warning changed from:
"... from 'jar:file:///path/to/helidon-webserver-2.2.2.jar!/META-INF/native-image/io.helidon.webserver/helidon-webserver/native-image.properties' ... "
to:
"... from 'META-INF/native-image/io.helidon.webserver/helidon-webserver/native-image.properties' in 'jar:file:///path/to/helidon-webserver-2.2.2.jar'"
> Update warning pattern for --allow-incomplete-classpath

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
The fix for record annotations will be part of 22.1 and is backported to 21.3.1.1 but it's not present in 22.0
> Disable recordAnnotationsWork test on 22.0

- .github/workflows/builder_image_tests.yml
- .github/workflows/local_tests.yml
- .github/workflows/testing_testsuite.yml
- pom.xml
- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
The report makes much more sense now:
```
[ERROR] imageioAWTTest{TestInfo}  Time elapsed: 0.121 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
A different set of static libraries was expected. 
Expected: [libawt.a, libawt_headless.a, libfdlibm.a, libfontmanager.a, libjava.a, libjavajpeg.a, libjvm.a, liblcms.a, liblibchelper.a, libmanagement_ext.a, libnet.a, libnio.a, libzip.a]
Actual:   [libawt.a, libawt_headless.a, libfdlibm.a, libfontmanager.a, libjava.a, libjavajpeg.a, libjvm.a, liblcms.a, liblibchelper.a, libnet.a, libnio.a, libzip.a] ==> expected: <true> but was: <false>
at org.graalvm.tests.integration.AppReproducersTest.imageioAWT(AppReproducersTest.java:485)
at org.graalvm.tests.integration.AppReproducersTest.imageioAWTTest(AppReproducersTest.java:359)
```
Let's see if the …
> native-image executable file searched for static libs linked

- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Avoids:
```
Error:  Failures: 
Error:    DebugSymbolsTest.debugSymbolsQuarkus:224 build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.DebugSymbolsTest/debugSymbolsQuarkus/build-and-run.log and check these offending lines: 
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.databind.util.ClassUtil$EnumTypeLocator ==> expected: <true> but was: <false>
Error:    RuntimesSmokeTest.quarkusFullMicroProfile:201->testRuntime:167 build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived …
```
> Whitelist warning for illegal reflective access

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
The comments in the code suggest that some code in graal master got added and removed again, but https://github.com/oracle/graal/commit/a0e6a3aeb8b63f6c06dc3554c342075534d90796 was actually added with PR https://github.com/oracle/graal/pull/4383. The JDK static lib is being used as the relevant class is reachable for that application.
Closes: #109
> Add libmanagement_ext.a as an expected static lib.

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
As discussed in #108. 
```
MethodHandles.lookup().lookupClass().getResourceAsStream("/com/sun/imageio/plugins/common/iio-plugin.properties")
```
and
```
Thread.currentThread().getContextClassLoader().getResourceAsStream("com/sun/imageio/plugins/common/iio-plugin.properties")
```
Changed from `N/A` to `JDK`. It doesn't seem to affect quarkus integration tests (`awt`).
Closes: #108
> Attempt test fix for resource locations

- builder-image-apps/quarkus-spöklik-encoding/threshold.properties
This has been around f a long time, nagging in reports. Anything that includes localization on RHEL 9 gets bigger than on RHEL 8. I am lifting the threshold.
> Locales/encoding related build gets bigger on RHEL9

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/JFRTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
Small UX improvement: If the executable fails to start, e.g. native image not built, it throws an NPE. JUnit failure is better in that case to understand for an uninitiated reader.
> Fail instead of throwing NPE when Process is null

- testsuite/src/it/java/org/graalvm/tests/integration/utils/GDBSession.java
https://github.com/oracle/graal/pull/5172 fixed this upstream issue https://github.com/oracle/graal/issues/5064. However, the test still asserted wrong data. Now stripped spaces in function parameters and not including a specific 'void' string for void functions.
Closes: #110
> Fix debug smoke test after improved mangle support

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
This patch explicitly sets `-Djava.awt.headless=true` everywhere so that we aren't at the whim of whatever `GraphicsEnvironment.isHeadless()` deems the currently running system is in terms of headful or headless. Apparently CI systems are different. This rules out a headful build.
After https://github.com/oracle/graal/pull/5122 is merged, we should have that test passing everywhere (including 23.0.0-dev and 22.3.0-dev - once we backport there).
First part to close #117.
> Don't expect management_ext.a for imageio test

- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
On GraalVM 23.x the warning includes `[...] resolve class[...]` over `[...] resolve com.orsoncharts[...]` in the message which the test didn't expect. Example warning on 23.x:
```
Warning: Could not resolve class com.orsoncharts.Chart3DHints for reflection configuration. Reason: java.lang.ClassNotFoundException: com.orsoncharts.Chart3DHints.
```
> Fix orsoncharts allowlist

- testsuite/src/it/java/org/graalvm/tests/integration/PerfCheckTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/QuarkusVersion.java
fixes #135 
It works as expected, I have this in DB now:
> Q 999-SNAPSHOT needs GIT SHA in report

- apps/versions/src/main/java/version/GraalVM20OrLater.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/NewVersionsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/UsedVersion.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/VersionsTest.java
An update so as to detect version strings like these as well:
```
native-image 17.0.6 2023-01-17
OpenJDK Runtime Environment Mandrel-23.1.0-dev (build 17.0.6+10)
OpenJDK 64-Bit Server VM Mandrel-23.1.0-dev (build 17.0.6+10, mixed mode)
```
> Update version detection for GraalVM 23.0+

- apps/imageio/src/main/java/imageio/Main.java
- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Please review this fix for the imageio integration tests so
that they work for 23+ GraalVM as well. The changes are
fairly minimal. Basically setting `java.home` property for
the native run and cleaning the font cache prior running
java with the native agent and prior running natively
(for symmetry).
Thoughts?
Closes: #143
> Fix imageio integration tests for 23+

- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/UsedVersion.java
This avoids the output getting polluted when `native-image --version` runs and it's output is getting parsed for version info.
Closes: #148
> Pull the image before running --version

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
It works both locally:
```
mvn clean verify -Ptestsuite -Dtest=AppReproducersTest#imageioAWTTest
```
and in a container:
```
mvn clean verify -Ptestsuite-builder-image -Dtest=AppReproducersTest#imageioAWTContainerTest -Dquarkus.native.builder-image=quay.io/karmkarm/ubi-quarkus-mandrel-builder-image:23.0-java20
```
How come it works in the container without creating those JAVA_HOME dirs in the container and copying .so files there?
It's because the TS mounts the app dir, parent o the target dir:
```
docker run -u 1000:1000 -t -v /home/karm/workspaceRH/mandrel-integration-tests-Apr2023/apps/imageio:/work:z my-imageio-runner /work/target/imageio -Djava.home=. -Djava.awt.headless=true
```
> Adds fake JAVA_HOME to appease FontConfig

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
New behaviour backported to 23.0 as well
https://github.com/oracle/graal/commit/eefeda1b94dd1a24aa6d1a557448a4e90d51c591
Relates to #154
> Update flags for DebugSymbolsSmoke test for GraalVM 23.0 as well

- testsuite/src/it/java/org/graalvm/tests/integration/utils/GDBSession.java
Waiting for `.*` results in essentially matching no output as well, which is not intended.
Fixes: #157
> Show version in gdb should return text including `gdb`

- testsuite/src/it/java/org/graalvm/tests/integration/utils/GDBSession.java
Fixes issue seen in https://github.com/graalvm/mandrel/actions/runs/5172441559/jobs/9317239703#step:11:18618
> Fix pattern for debug symbols smoke test when using JDK 21

- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/CP.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/GDBSession.java
Increases timeout for setting breakpoint in `DebugSymbolsTest#debugSymbolsQuarkus`.
Avoids failures due to https://github.com/Karm/mandrel-integration-tests/issues/160
The timeout should be revisited once we conclude on whether such a delay on loading the symbols is acceptable or not.
> Increase timeout for DebugSymbolsTest#debugSymbolsQuarkus

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
That native library has been ported to Java and is, thus, no longer part of the link for the imageio application.
Closes #164
> Don't expect libfdlibm.a for JDK 21+

- testsuite/src/it/java/org/graalvm/tests/integration/utils/GDBSession.java
As mentioned in https://github.com/Karm/mandrel-integration-tests/issues/160#issuecomment-1580198623 5 minutes are not enough on github actions.
Relates to https://github.com/Karm/mandrel-integration-tests/issues/160
> Further increase timeout for DebugSymbolsTest#debugSymbolsQuarkus

- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/GDBSession.java
https://github.com/oracle/graal/pull/6984 reduced the time spent reading debyg symbols but it's still noticeable. This PR re-adjusts the timeouts to a timeout of 60 seconds.
Relates to #160
> Adjust timeouts for waiting GDB to read debug symbols

- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
Instead of waiting till the gdb output matches the expected command or timeouts, wait for the command to complete (or timeout), i.e. for the prompt to appear. This way if a command prints the expected output but doesn't complete, it's execution time is not being counted by the next `waitForBufferToMatch` invocation, additionally if the command completes but doesn't return the expected result we don't have to wait for the timeout. Furthermore, we can enhance the logging to see if the command timed out or completed but without matching the expected output.
To ensure the prompt appears consistently across gdb versions after every command we use the GDB/MI mode, i.e. the "--interpreter=mi" option.
Closes https://github.com/Karm/mandrel-integration-tests/issues/173
> Improve handling of gdb commands

- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
1. Log output after waiting for the buffer to match the expected pattern (ensures log will contain the actual ouput)
2. Log the time it took for the buffer to match the expected pattern
3. Change the way log sections are used (include command and output in the same section)
> Enhance gdb commands logging

- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
Regression caused by fed26dd, happens for some *podman* settings on command line, e.g. 
```
mvn clean verify -Ptestsuite-builder-image -Dquarkus.version=3.2.3.Final -Dquarkus.native.container-runtime=podman
```
must work too. Not just QUARKUS_NATIVE_CONTAINER_RUNTIME env prop.
> Smart getProperty(... was too smart with container runtime property

- .github/workflows/builder_image_tests.yml
- .github/workflows/local_tests.yml
Also switch to `temurin` distro in setup-java. `adopt` is deprecated.
> Skip 21.3 testing in CI

- apps/imageio/src/main/java/imageio/Main.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
Resources don't need to get explicitly added with the CLI option, since the java run with the agent, will generate appropriate resource-config.json files which are sufficient for the resources to get added.
By removing `-H:IncludeResources` we no longer get the experimental VM warnings on 23.1+ (#186).
> Fix imageio test for 23.1+

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
The graal-sdk split has, as a corollary, moved the HomeFinder API to the polyglot.jar artefact. Since Mandrel doesn't include this in a default install anymore, disable that test.
Closes: #182
> Disable versions test for 23.1+

- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
The helidon native-image build is being driven by the helidon-maven-plugin which doesn't allow for unlocking certain parameters which the maven-plugin itself is adding. Therefore, allow list the newly produced warnings for now.
Closes: #189
> Allow list log lines for helidon

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
The earlier fix missed to exclude 23.1 as the condition was 23.1.0.0-dev<sha> <= 23.1 which is true (wrong). What we actually want is to run it up to and including to 23.0. Latest release is 23.0.1, so up to a max value of 23.0 doesn't work either, since that would amount to 23.0.1 <= 23.0.0 which is false. Use 23.0.99 as the comparison value instead.
> Fix version test exclusion

- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Those are out of our control and quarkus would need a netty update to deal with this.
Closes #190 and #201. Final piece of #188.
> Allow-list netty experimental VM options lines

- testsuite/src/it/java/org/graalvm/tests/integration/JFRTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
Related issue: https://github.com/Karm/mandrel-integration-tests/issues/211
This PR does a bit of rearranging to try to reduce duplicate JFR perf test app builds. I've just moved the build up a few levels so its done in `jfrPerfTestRun` and can be reused for multiple hyperfoil benchmarks. I also moved the cleanup code too.  And I did some minor renaming for consistency.
> Reduce the number of builds during JFR perf test

- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/PerfCheckTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/RuntimesSmokeTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/IfQuarkusVersion.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/QuarkusVersionCondition.java
Works around https://github.com/Karm/mandrel-integration-tests/issues/223 to get CI passing till it gets fixed.
One major drawback, other than the obvious one of skipping three good tests in Quarkus >= 3.6.0 is that we skip them for any SNAPSHOT build as well even for Quarkus < 3.6.0.
> Temporary work around: Disable quarkus-full-microprofile dependent tests

- apps/quarkus-full-microprofile/quarkus_3.6.x.patch
- apps/quarkus-full-microprofile/threshold.properties
- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/PerfCheckTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/RuntimesSmokeTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Logs.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Fixes #225 
```
$ mvn clean verify -Ptestsuite 
-Dtest=RuntimesSmokeTest#quarkusFullMicroProfile,DebugSymbolsTest#debugSymbolsQuarkus,PerfCheckTest#testQuarkusFullMicroProfile 
-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21 
-DincludeTags=runtimes,reproducers,perfcheck -Dquarkus.version=3.6.0 | tee log.log 
```
passes now.
> FullMicroprofile ported to new tracing API, MP6+ Q3.6+

- .github/workflows/builder_image_tests.yml
- .github/workflows/local_tests.yml
- .github/workflows/testing_testsuite.yml
- apps/quarkus-vertx/quarkus_3.x.patch
- pom.xml
- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/PerfCheckTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/RuntimesSmokeTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Apps.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/GDBSession.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/URLContent.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/QuarkusVersion.java
> Builder image: Ports debug Vertx app to Reactive, bumps Q versions

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/StaticDistroChecks.java
Leaving resource locations there on purpose, it seems a neat way to see the difference over time.
> Removed Mandrel 21 only test methods

- .github/workflows/builder_image_tests.yml
- .github/workflows/local_tests.yml
It seems practical for certain parts of the TS to be able to run old Mandrel/Quarkus.
I will let this run the whole CI and then use annotations to restrict it only to parts where it makes sense, e.g. FullMicroProfile app.
> Reintroduce Mandrel 21 sanity test

- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
This is a follow up to: https://github.com/Karm/mandrel-integration-tests/pull/238 
https://github.com/oracle/graal/pull/8037#event-11298904545 Has now been merged ([internal PR](https://github.com/oracle/graal/pull/8057)), so I've adjusted the whitelisted lines. 
This should prevent things form breaking when the latest JDK and GraalVM master are used. 
This PR replaces the old whitelisted lines. I'm not sure if that's the right thing to do (in case there is a test configuration that uses a development version that isn't the latest GraalVM master). I can add the old whitelisted lines back in if that's the case.
> Update whitelisted JFR log lines once more

- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/PerfCheckTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/RuntimesSmokeTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/QuarkusVersion.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/QuarkusVersionTest.java
See
https://github.com/quarkusio/quarkus/blob/3c8c772dda9ed99674c9d8a6cd9cb4635d1ce5a2/build-parent/pom.xml#L8
and
https://github.com/quarkusio/quarkus/blob/bc0ca288d32ba2df212d8c4a2783c0bb21ca99a1/build-parent/pom.xml#L8
Relates to https://github.com/graalvm/mandrel/issues/501
> Update quarkus version checks to adapt to new SNAPSHOT versions

- .github/workflows/builder_image_tests.yml
- .github/workflows/local_tests.yml
- apps/jfr-native-image-performance/quarkus_3.9.x.patch
- apps/quarkus-json/quarkus_3.9.x.patch
- apps/quarkus-vertx/quarkus_3.9.x.patch
- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/JFRTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/PerfCheckTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/QuarkusVersion.java
> Quarkus renaming REST extensions

- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
The fix from #265 was incomplete. The JFR perf tests use the JFR config for allow-listed log lines.
The `JFRTest.jfrPerfTest` uses this code:
```
public void jfrPerfTestRun(TestInfo testInfo, boolean inContainer) throws IOException, InterruptedException {
final Apps appJfr = inContainer ? Apps.JFR_PERFORMANCE_BUILDER_IMAGE : Apps.JFR_PERFORMANCE;
final Apps appNoJfr = inContainer ? Apps.PLAINTEXT_PERFORMANCE_BUILDER_IMAGE : Apps.PLAINTEXT_PERFORMANCE;
```
... and both `Apps.JFR_PERFORMANCE` and `Apps.PLAINTEXT_PERFORMANCE` use `WhitelistLogLines.JFR` config which this patch is fixing.
> Allow list old Mandrel version warning for JFR perf tests

- apps/jfr-native-image-performance/src/main/docker/Dockerfile.native
- apps/monitor-field-offset/Dockerfile
- apps/monitor-field-offset/pom.xml
- apps/monitor-field-offset/src/main/java/monitor_field_offset/Main479.java
- apps/monitor-field-offset/src/main/java/monitor_field_offset/Main480.java
- apps/quarkus-spöklik-encoding/src/main/docker/Dockerfile.native
- apps/quarkus-vertx/src/main/docker/Dockerfile.native
- pom.xml
- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Apps.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/ContainerNames.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Adds a test guarding against a possible regression in future. The compiler should not allow you to compile an unsupported source file. There was no warning in older versions and there is one now.
Tested on Linux amd64, aarch64 and MacOS aarch64 so far prior opening the PR.
> Monitor field offset test

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/AuxiliaryOptions.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Surpasses #276 
Fixes #262 
@jerboaa So, this is unrelated to https://github.com/oracle/graal/issues/9300. JDK 24 with Graal master now requires `-H:+ForeignAPISupport`. I will have to take a look at it in Quarkus too.
```
Exception in thread "main" java.io.IOException: Problem reading font data.
at java.desktop@24-internal/java.awt.Font.createFont0(Font.java:1205)
at java.desktop@24-internal/java.awt.Font.createFont(Font.java:1076)
at imageio.Main.loadFonts(Main.java:139)
at imageio.Main.paintRectangles(Main.java:97)
at imageio.Main.main(Main.java:195)
at java.base@24-internal/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Support for the Java Foreign Function and Memory API is not active: enable with …
```
> ImageIO requires -H:+ForeignAPISupport to try to lookup fonts

- apps/for-serialization/Dockerfile
- apps/for-serialization/pom.xml
- apps/for-serialization/src/main/java/for_serialization/Main.java
- pom.xml
- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Apps.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/ContainerNames.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
* Depends on https://github.com/oracle/graal/issues/8509 being released via https://github.com/graalvm/graalvm-community-jdk21u/pull/10
* Depends on https://github.com/oracle/graal/issues/9581 being fixed, backported and released.
Merging it now would trigger failures for CI.
> Tests config for serialization of arrays

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
https://github.com/oracle/graal/pull/9091 is only present in >= 24.2 (GraalVM for JDK 24) and
23.1.xxx (GraalVM for JDK 21)
Both 24.0 and 24.1 don't include the fix and are expected to fail.
See https://github.com/graalvm/mandrel/actions/runs/10908619717/job/30276316555
> Update version range for Serialization tests

- apps/for-serialization/src/main/java/for_serialization/Main.java
- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
Works around https://github.com/oracle/graal/issues/9581 to [avoid CI noise](https://github.com/Karm/mandrel-integration-tests/issues/282#issuecomment-2376449083)
> Disable String[] check in serialization test

- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
This should fix failures due to new warnings coming from the JDK in the following tests:
- DebugSymbolsTest.debugSymbolsQuarkus
- JFRTest.jfrPerfTest
- RuntimesSmokeTest.quarkusFullMicroProfile
Closes: #284
> Allow-list brotli warning after JEP 472

- testsuite/src/it/java/org/graalvm/tests/integration/PerfCheckTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/RuntimesSmokeTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
Closes https://github.com/Karm/mandrel-integration-tests/issues/290
> Start Jaeger to avoid errors related to opentracing/opentelemetry

- apps/quarkus-spöklik-encoding/threshold.conf
- testsuite/src/it/java/org/graalvm/tests/integration/RuntimesSmokeTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
There is a combination of Podman version and Java version where this piece of code hangs indefinitely:
```java
final URLConnection c = new URL(url).openConnection();
c.setRequestProperty("Accept", "*/*");
c.setConnectTimeout(500);
try (Scanner scanner = new Scanner(c.getInputStream(), StandardCharsets.UTF_8)) {
^^^^^^^^^^^^^^^^^
scanner.useDelimiter("\\A");
webPage = scanner.hasNext() ? scanner.next() : "";
}
```
on Scanner trying to read the input stream.  It seems that what used to be rather simple:
a) an exception is thrown, because Quarkus is not yet ready
b) a request response is populated in the buffer and read
is now more convoluted with some third state 
c) no exception is thrown, but the buffer is not populated, Scanner hangs
I included a check for word `started` in the container …
> Race condition with RHEL9 Podman version, Whitelists, Thresholds

- apps/jdkreflections/pom.xml
- apps/jdkreflections/src/main/java/jdkreflections/Main.java
- pom.xml
- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Apps.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/ContainerNames.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Embeds a variation on the reproducer @zakkak outlined on the original issue.
This forces the native agent to register e.g. the `getNextThreadIdOffset` that later causes 
```
/bin/ld: jdkreflections.o:(.data+0x7b8): undefined reference to `Java_java_lang_Thread_getNextThreadIdOffset'
```
Fails with current Mandrel for JDK 21, passes with e.g. Mandrel for JDK 23.
```
mvn clean verify -Dquarkus.version=3.15.1 -Ptestsuite -Dtest=AppReproducersTest#jdkReflectionsTest
```
or in a container:
```
mvn clean verify -Ptestsuite-builder-image 
-Dtest=AppReproducersTest#jdkReflectionsContainerTest -Dquarkus.version=3.15.1
-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-23
-Dquarkus.native.container-runtime=podman
-Drootless.container-runtime=true …
```
> Tests graalvm-community-jdk21u-issues-28

- testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/GDBSession.java
GDB appears to take longer to load symbols in `graal/master` builds than
it used to in 24.1.1.
24.1.1
```
gdb -q target/debug-symbols-smoke < gdb.commands  2.27s user 0.06s system 101% cpu 2.288 total
```
`graalm/master`
```
gdb -q target/debug-symbols-smoke < gdb.commands  3.01s user 0.05s system 102% cpu 2.995 total
```
> Increase timeout for `info functions .*smoke.*` gdb command

- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
I wouldn't say "fixes" but it temporarily
workarounds #314
Tested on windows:
```
C:\tmp\mandrel-integration-tests(24-25-windows -> origin)
λ  mvn clean verify -Dquarkus.version=3.8.6 -Ptestsuite -Dtest=AppReproducersTest#forSerializationPost24_2Test
...
2025-03-14 01:59:06.955 INFO  [o.g.t.i.u.v.UsedVersion$MVersion] (of) The test suite runs with Mandrel version 25.0.0-devd8d7b2fe0cc installed locally on PATH, JDK 25.0.0.
...
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 269.059 s - in org.graalvm.tests.integration.AppReproducersTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
```
Notes:
1) I wonder why Linux GHA doesn't complain about it, my Maven 3.9.9 does emit these JNI and Unsafe warnings with JDK 25
2) …
> JDK 24/25 related warnings, temporary

- testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
Historically, this TS assumed docker-ce the default container runtime. That has changed over the years to a point where we have either Podman or Podman Desktop installed everywhere and we keep cluttering test envs with an explicit switch to podman.
A notable exception is GHA.
I think we can switch the default to podman now...
> Changes default container runtime to podman

- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
We did allow list certain log lines in #316. This wasn't sufficient since that only allowed those log lines for the `forSerialization` test, but not for the `jdkReflections` test. This fixes it.
From CI:
```
2025-04-01 01:26:19.707 INFO  [o.g.t.i.u.Logs] (checkLog) build-and-run.log log for forSerializationPost24_2Test contains whitelisted error: `com.oracle.svm.configure.trace.AccessAdvisor: Warning: Observed unexpected JNI call to GetStaticMethodID (map(size=7, {(tracer,jni),(function,GetStaticMethodID),(class,java.lang.Boolean),(declaring_class,java.lang.Boolean),(caller_class,jdk.internal.loader.NativeLibraries$NativeLibraryImpl),(result,true),(args,[getBoolean, (Ljava/lang/String;)Z])})). Tracing all subsequent JNI accesses.'
```
OK. But then we get:
```
Error: …
```
> Allow list log line for jdkReflection test on Windows

- apps/jfr-native-image-performance/src/main/java/org/acme/getting/started/GreetingService.java
- testsuite/src/it/java/org/graalvm/tests/integration/JFRTest.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
This is just a small fix to correct the way the binary size is obtained.  Previously, we were getting the size of the first file in the directory that ended in _"-runner"_. This resulted in obtaining the size of the same file twice. 
I've also changed the JFR configuration to be based on profile.jfc. This should cause JFR to work a little bit harder.
> Minor JFR fix for obtaining image size

- testsuite/src/it/java/org/graalvm/tests/integration/StaticDistroChecksTest.java
I propose to call `native-image --version` directly. Not go the `bash native-image --version` indirection. Not sure if that will break anything. It works for my testing. Thoughts, @Karm?
Closes: #332
> Fix StaticDistroChecksTest for GraalVM CE builds

- testsuite/src/it/java/org/graalvm/tests/integration/utils/Apps.java
- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Allow maven 3.9.10 warnings that we cannot influence.
Closes: #341
> Allow list maven 3.9.10 warnings with JDK 25

- testsuite/src/it/java/org/graalvm/tests/integration/utils/GDBSession.java
Using the existing `increasedTimeoutMS` which is set to 80000ms.  This might be appear as too high, but we already use it for other commands taking 10-15 secs, like the first breakpoint command, as we have seen some pretty slow VMs hitting the timeout if it's not high enough.
Reusing an existing value also keeps things simpler.
Closes https://github.com/Karm/mandrel-integration-tests/issues/360
> Increase timeout for backtrace command in debugSymbolsQuarkus

- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Previously this was done on JDK 26+, but with the recent reversion of graal/master being JDK 25-based again we don't get the allow-listed warnings matched anymore.
Instead of doing a new version parsing scheme (again!) we just match the version 25+ as it should do no harm to match this on Mandrel 25 as well.
Closes: #369
> Allow list new warnings message on JDK 25+

- testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
I Added two Perf errors, which were seen in the CI, to the QUARKUS_FULL_MICROPROFILE's log whitelist.
Fixes #372.
> Added Perf errors to the QUARKUS_FULL_MICROPROFILE's log whitelist
