Karm/mandrel-integration-tests

builder-image-apps/quarkus-spöklik-encoding/threshold.properties, testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java, testsuite/src/it/java/org/graalvm/tests/integration/RuntimesSmokeTest.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/Apps.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/ContainerNames.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/LogBuilder.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/Logs.java
- containers are properly stopped on Windows now
- memory is collected from the docker stats, not the docker process itself
- works with podman and docker on Linux (Fedora, RHEL)
- works with docker on Windows
K.
=> Docker on Windows support, Podman support

apps/quarkus-full-microprofile/src/main/java/com/example/quarkus/secure/TestSecureController.java, apps/quarkus-full-microprofile/src/main/resources/application.properties, pom.xml
Master support Quarkus 2.x and Mandrel 21.1+.
Quarkus 1.11.x and Mandrel 20.3.y is in branch quarkus-1.11.x-mandrel-20.3.y.
=> Quarkus 2.x

apps/quarkus-full-microprofile/pom.xml, apps/quarkus-full-microprofile/quarkus_1.x.patch, apps/timezones/pom.xml, builder-image-apps/quarkus-spöklik-encoding/pom.xml, builder-image-apps/quarkus-vertx/pom.xml, builder-image-apps/quarkus-vertx/src/main/docker/Dockerfile.native, pom.xml, testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java, testsuite/src/it/java/org/graalvm/tests/integration/RuntimesSmokeTest.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/Apps.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/URLContent.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
* the TS can run with Podman now
* it can switch Quarkus Version via env var or command argument
* addresses differences between Quarkus 1.x and Quarkus 2.x WRT MicroProfile
=> Podman migration, Quarkus version runtime switch, stabilization

testsuite/src/it/java/org/graalvm/tests/integration/utils/GDBSession.java
=> Add `show version` to gdb commands

testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Works around https://github.com/Karm/mandrel-integration-tests/issues/68 until a better solution gets implemented.
=> Whitelist GC warnings

testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
Pros:
1. Makes it easier to detect issues on CI, without having to download the build logs, extract, and look them up.
2. Makes it easier to see that there is progress and the build is not stuck.
Cons:
1. Makes the output a bit noisy.
=> Dump processes' output to standard output in addition to the log file

testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/GDBSession.java
=> Workaround graalvm/mandrel#355

testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
=> Fix adding to unmodifiable Set

testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
=> Fix resource locations expected output for GraalVM >= 23.0

apps/recordannotations/pom.xml
=> Annotations are supported in JDK >= 17

apps/debug-symbols-smoke/threshold.properties, apps/quarkus-spöklik-encoding/threshold.properties, testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java, testsuite/src/it/java/org/graalvm/tests/integration/RuntimesSmokeTest.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/LogBuilder.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Check if executable exists first
amd64/arm64 Hyperfoil, thresholds props
Fiddle with CPU boost only where supported
Cleanup imageio cache font files, Whitelist podman
Relaxes <= 0 to < 0 for measurements as diff of size 0 is valid
=> Improves aarch64 compatibility (hyperfoil), plus small fixes

apps/quarkus-json/pom.xml, apps/quarkus-vertx/pom.xml, apps/quarkus-vertx/quarkus_3.x.patch, testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java
In some environments where the maven repository cache is clean you can run into the problems as described in the linked issue.
Closes #183
=> Fixes in maven projects

testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java, testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java, testsuite/src/it/java/org/graalvm/tests/integration/PerfCheckTest.java, testsuite/src/it/java/org/graalvm/tests/integration/RuntimesSmokeTest.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java
Related to #184 
Closes #187 
Fixes part of #188 and #190
=> Wrap experimental commands in -H:+-UnlockExperimentalVMOption where necessary

testsuite/src/it/java/org/graalvm/tests/integration/JFRTest.java
=> Wrap SignalHandlerBasedExecutionSampler in UnlockExperimentalVMOptions

testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/UsedVersion.java
Simple mapping to get a GraalVM version based on the JDK major version. This would defer needing to make a decision whether or not we want to use the `release`/`mandrel.release` files instead.
Closes #209
=> Fix Mandrel IT runs with JDK 22-based builds

testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Closes: https://github.com/Karm/mandrel-integration-tests/issues/239
=> Update JFR whitelisted log lines

apps/debug-symbols-smoke/threshold.conf, apps/helidon-quickstart-se/threshold.conf, apps/jfr-native-image-performance/threshold.conf, apps/quarkus-full-microprofile/threshold.conf, apps/quarkus-spöklik-encoding/threshold.conf, testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java, testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java, testsuite/src/it/java/org/graalvm/tests/integration/JFRTest.java, testsuite/src/it/java/org/graalvm/tests/integration/PerfCheckTest.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/Logs.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Makes the TS run on our M2 Pro mac mini system. The one with Rosetta.
Pending tests without Rosetta....
=> macOS port

testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
=> Add allow list for older Mandrel release with quarkus main.

testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Note that I've also added another allow-list entry that my local maven spits out. I couldn't get the tests to pass otherwise. Hope that's OK.
Closes: #261
=> Allow lists for changed metadata config files

testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
=> Allow list proxy config warning for JFR tests

testsuite/src/it/java/org/graalvm/tests/integration/DebugSymbolsTest.java
=> Fix readiness check for db in debugSymbolsQuarkusContainer

testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/UsedVersion.java
Drop everything until we see "GraalVM" or "native-image" in the output.
This way we can ignore warnings and other output that might be present.
Fixes https://github.com/Karm/mandrel-integration-tests/issues/293
=> Ignore irrelevant output when parsing Mandrel version

testsuite/src/it/java/org/graalvm/tests/integration/utils/Logs.java
Related to https://github.com/Karm/mandrel-integration-tests/issues/290
=> Check logs for SEVERE messages as well

apps/jfr-native-image-performance/src/main/java/org/acme/getting/started/GreetingService.java, testsuite/src/it/java/org/graalvm/tests/integration/JFRTest.java
This is just a small fix to resolve: https://github.com/Karm/mandrel-integration-tests/issues/297
I also add a guard against divide by zero errors. 
Thanks!
=> JFR test fixes

testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Closes: https://github.com/Karm/mandrel-integration-tests/issues/304
=> Whitelist warnings about terminally deprecated `Unsafe` methods

testsuite/src/it/java/org/graalvm/tests/integration/utils/GDBSession.java
Place the increased timeout in the correct if statement.
=> Fix up https://github.com/Karm/mandrel-integration-tests/pull/308

.github/workflows/builder_image_tests.yml, .github/workflows/local_tests.yml, .github/workflows/testing_testsuite.yml, testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
=> Fixes maven sources warning

testsuite/src/it/java/org/graalvm/tests/integration/utils/Logs.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Concerns https://github.com/Karm/mandrel-integration-tests/pull/316
=> Count loglines, Windows whitelist

apps/imageio/Dockerfile.amzn1, apps/imageio/Dockerfile.amzn2, apps/imageio/Dockerfile.amzn2023, apps/imageio/Dockerfile.cnts10, apps/imageio/Dockerfile.ubi8, apps/imageio/Dockerfile.ubi9, apps/imageio/Dockerfile.ubnt2204, apps/imageio/Dockerfile.ubnt2404, apps/imageio/src/main/java/imageio/Main.java, testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/Commands.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
Prepared to run with https://github.com/quarkusio/quarkus-images/issues/287
=> AWT Container: amzn2, amzn2023, ubi9, ubi8, ubnt2204, ubnt2404

apps/vthread_props/Dockerfile.amzn2, apps/vthread_props/Dockerfile.amzn2023, apps/vthread_props/Dockerfile.cnts10, apps/vthread_props/Dockerfile.ubi10, apps/vthread_props/Dockerfile.ubi8, apps/vthread_props/Dockerfile.ubi9, apps/vthread_props/Dockerfile.ubnt2204, apps/vthread_props/Dockerfile.ubnt2404, apps/vthread_props/pom.xml, apps/vthread_props/src/main/java/vthread_props/Main.java, pom.xml, testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/Apps.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java, testsuite/src/it/java/org/graalvm/tests/integration/utils/ContainerNames.java
Tests issue related to: https://github.com/oracle/graal/pull/10109/files as a part of backports testing.
=> Tests runtime and sys props from virtual threads

testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/UsedVersion.java
Use the JDK version bits for the GraalVM version when there is no mapping for JDK 22+
Closes: #348
=> Fix version parsing for JDK 26+ based GraalVM
